# Generated by Django 2.0.7 on 2018-10-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userworks', '0002_userworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworks',
            name='cust_regid',
        ),
    ]
