# Generated by Django 2.0.7 on 2018-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userworks', '0003_remove_userworks_cust_regid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworks',
            name='cust_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userworks',
            name='custemail',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userworks',
            name='custname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userworks',
            name='custphno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
