# Generated by Django 2.0.7 on 2018-10-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approach',
            old_name='empneeded',
            new_name='empavail',
        ),
    ]
