# Generated by Django 2.0.7 on 2018-10-14 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0002_auto_20181014_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
