# Generated by Django 2.0.7 on 2018-10-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0003_approach_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approach',
            old_name='date',
            new_name='cdate',
        ),
        migrations.AddField(
            model_name='approach',
            name='con_id',
            field=models.BigIntegerField(default=1.0),
            preserve_default=False,
        ),
    ]
