# Generated by Django 2.0.7 on 2018-10-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0004_auto_20181014_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='empname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
