# Generated by Django 2.0.7 on 2018-10-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0006_auto_20181014_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='work_id',
        ),
    ]
