# Generated by Django 2.0.7 on 2018-10-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0007_remove_approach_work_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='work_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
