# Generated by Django 2.0.7 on 2018-10-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0008_approach_work_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='cust_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approach',
            name='cust_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
