# Generated by Django 2.0.7 on 2018-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0009_auto_20181027_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='cust_name',
        ),
        migrations.AddField(
            model_name='approach',
            name='custname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
