# Generated by Django 2.0.7 on 2018-10-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0010_auto_20181027_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='con_id',
        ),
        migrations.RemoveField(
            model_name='approach',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='approach',
            name='custname',
        ),
        migrations.RemoveField(
            model_name='approach',
            name='work_id',
        ),
    ]
