# Generated by Django 2.0.7 on 2018-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0011_auto_20181027_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='con_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approach',
            name='cust_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approach',
            name='custname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='approach',
            name='work_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
