# Generated by Django 2.0.7 on 2018-11-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0012_auto_20181027_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='work_id',
        ),
    ]
