# Generated by Django 2.0.7 on 2018-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0013_remove_approach_work_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='work_id',
            field=models.BigIntegerField(default=5),
            preserve_default=False,
        ),
    ]
