# Generated by Django 2.0.7 on 2018-08-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('cust_mailid', models.CharField(default='', max_length=30)),
                ('cust_phno', models.CharField(default='', max_length=10)),
                ('cust_aadharno', models.CharField(default='', max_length=20)),
                ('cust_address', models.CharField(default='', max_length=50)),
                ('cust_street', models.CharField(default='', max_length=50)),
                ('cust_city', models.CharField(default='', max_length=50)),
                ('cust_pin', models.CharField(default='', max_length=6)),
                ('cust_district', models.CharField(default='', max_length=30)),
                ('cust_uname', models.CharField(default='', max_length=30)),
                ('cust_pswd', models.CharField(default='', max_length=15)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.State')),
            ],
        ),
    ]
