# Generated by Django 2.0.7 on 2018-08-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_reg',
            name='cust_mailid',
        ),
        migrations.RemoveField(
            model_name='customer_reg',
            name='cust_uname',
        ),
    ]
