# Generated by Django 2.0.7 on 2018-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_reg', '0002_auto_20180822_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_reg',
            name='cust_mailid',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer_reg',
            name='cust_uname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
