# Generated by Django 2.0.7 on 2018-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='con_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
