# Generated by Django 2.0.7 on 2018-11-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_con_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='con_id',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='con_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor_reg.contractor_reg'),
        ),
    ]
