# Generated by Django 2.0.7 on 2018-11-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_reg', '0003_auto_20180822_1218'),
        ('feedback', '0003_auto_20181110_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cust_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_reg.Customer_Reg'),
            preserve_default=False,
        ),
    ]
