# Generated by Django 2.0.7 on 2018-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_id', models.BigIntegerField()),
                ('con_name', models.CharField(default='', max_length=30)),
                ('amt', models.CharField(default='', max_length=10)),
                ('phno', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
