# Generated by Django 2.0.7 on 2018-08-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancers_reg',
            name='freelancer_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
