# Generated by Django 2.0.7 on 2018-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_reg', '0002_contractor_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor_reg',
            name='con_status',
            field=models.BigIntegerField(default='0'),
        ),
    ]
