# Generated by Django 2.0.7 on 2018-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_reg', '0003_auto_20180901_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor_reg',
            name='mail_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
