# Generated by Django 2.0.7 on 2018-11-11 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractor_reg', '0006_remove_contractor_reg_confirmpswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.BigIntegerField()),
                ('cdate', models.DateField(default=datetime.date.today)),
                ('complaint', models.CharField(default='', max_length=100)),
                ('contractor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor_reg.contractor_reg')),
            ],
        ),
    ]
