# Generated by Django 2.0.7 on 2018-08-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructingcategory', '0001_initial'),
        ('contractor_reg', '0002_contractor_reg'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(default='', max_length=80)),
                ('constructioncat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructingcategory.ConstructingCategory')),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor_reg.contractor_reg')),
            ],
        ),
    ]
