# Generated by Django 2.0.7 on 2018-09-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20180901_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='work_category',
        ),
    ]
