# Generated by Django 2.0.7 on 2018-09-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_remove_works_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='contractor_id',
            field=models.BigIntegerField(),
        ),
    ]
